<?php

########################################################################
# Extension Manager/Repository config file for ext: "qm_configuration"
#
# Auto generated by Extension Builder 2014-03-31
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'QmConfiguration',
    'description' => "This extension offers simple static methods to fetch the configuration (LocalConfiguration, ext_conf_template and TypoScript) of any extension from both frontend and backend.",
    'category' => 'be',
    'author' => 'Guy Couronné',
    'author_email' => 'guy.couronne@qcmedia.ca',
    'author_company' => 'QcMédia',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.0.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '4.5.0-6.2.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
