<?php

########################################################################
# Extension Manager/Repository config file for ext: "qm_configuration"
#
# Auto generated by Extension Builder 2014-03-31
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'QmConfiguration',
	'description' => 'Extension allowing getting configuration of an extension from everywhere.',
	'category' => 'be',
	'author' => 'Guy Couronné',
	'author_email' => 'guy.couronne@qcmedia.ca',
	'author_company' => 'QcMédia',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>